apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    kubeQPS: 100
    kubeBurst: 500
    logLevel: error
    logFormat: json
    route:
      routes:
      - drop:
        - reason: "DNSConfigForming"
        match:
        - receiver: "dump"
    receivers:
      - name: "dump"
        stdout: {}
